(setq debug-on-error t)
(eval-when-compile (require 'cl))
(delete-other-windows)
(eval-after-load 'nxhtml '(setq nxhtml-skip-welcome t))
(setq nxhtmltest-default-fontification-method 'fontify-w-timer-handlers)
